### ISSUE TITLE
top_metrics aggregations Missing required property 'TopMetricsAggregate.buckets'

### ISSUE THREAD

**Issue by silencewood** [elastic/elasticsearch-java#123]
top_metrics  response not have buckets is just top

{
	"key": 2189158,
	"doc_count": 2,
	"top_metrics_response": {
		"top": [
			{
				"sort": [
					"2022-01-20T09:52:51.191Z"
				],
				"metrics": {
					"metric_field1": "a",
					"metric_field2": "b",
					"metric_field3": "c"
				}
			}
		]
	}
}

when parse response  throw exception

Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'TopMetricsAggregate.buckets'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.MultiBucketAggregateBase.<init>(MultiBucketAggregateBase.java:59) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.TopMetricsAggregate.<init>(TopMetricsAggregate.java:48) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.TopMetricsAggregate.<init>(TopMetricsAggregate.java:44) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.TopMetricsAggregate$Builder.build(TopMetricsAggregate.java:88) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.TopMetricsAggregate$Builder.build(TopMetricsAggregate.java:70) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$Deserializer.deserialize(ExternallyTaggedUnion.java:66) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserializeEntry(ExternallyTaggedUnion.java:107) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.MultiBucketBase.lambda$setupMultiBucketBaseDeserializer$0(MultiBucketBase.java:161) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.parseUnknownField(ObjectDeserializer.java:205) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:174) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:320) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:285) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer$SingleMemberHandler.deserialize(UnionDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer.deserialize(UnionDeserializer.java:292) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer.deserialize(UnionDeserializer.java:259) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$Deserializer.deserialize(ExternallyTaggedUnion.java:66) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserializeEntry(ExternallyTaggedUnion.java:107) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.elasticsearch._types.aggregations.MultiBucketBase.lambda$setupMultiBucketBaseDeserializer$0(MultiBucketBase.java:161) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.parseUnknownField(ObjectDeserializer.java:205) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:174) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:320) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:285) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer$SingleMemberHandler.deserialize(UnionDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer.deserialize(UnionDeserializer.java:292) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.UnionDeserializer.deserialize(UnionDeserializer.java:259) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$Deserializer.deserialize(ExternallyTaggedUnion.java:66) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserializeEntry(ExternallyTaggedUnion.java:107) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:90) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ExternallyTaggedUnion$TypedKeysDeserializer.deserialize(ExternallyTaggedUnion.java:78) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:56) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.transport.rest_client.RestClientTransport.access$200(RestClientTransport.java:60) ~[elasticsearch-java-7.16.2.jar:na]
	at co.elastic.clients.transport.rest_client.RestClientTransport$1.onSuccess(RestClientTransport.java:165) ~[elasticsearch-java-7.16.2.jar:na]

**Comment by swallez** [comment]
The upstream API specification has been fixed in https://github.com/elastic/elasticsearch-specification/pull/1327

The next pass of code generation will fix the issue.
