### ISSUE TITLE
[es/snapshot.create] Missing required property 'CreateSnapshotResponse.snapshot'

### ISSUE THREAD

**Issue by jloisel** [elastic/elasticsearch-java#132]
Logs:

```
co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'CreateSnapshotResponse.snapshot'
	at co.elastic.clients.elasticsearch.snapshot.CreateSnapshotResponse$Builder.build(CreateSnapshotResponse.java:111)
	at co.elastic.clients.elasticsearch.snapshot.CreateSnapshotResponse$Builder.build(CreateSnapshotResponse.java:149)
	at co.elastic.clients.elasticsearch.snapshot.CreateSnapshotResponse.<init>(CreateSnapshotResponse.java:50)
	at co.elastic.clients.elasticsearch.snapshot.CreateSnapshotResponse.<init>(CreateSnapshotResponse.java:61)
					co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'CreateSnapshotResponse.snapshot'
```

Java code which creates the snapshot:

```java
    final CreateSnapshotRequest request = new CreateSnapshotRequest
      .Builder()
      .repository(repository)
      .snapshot(name)
      .ignoreUnavailable(true)
      .includeGlobalState(true)
      .build();

client.create(request);
```

The snapshot is successfully created on Elasticsearch, but the code fails to parse the response from the server, which simply returns:

```json
{
  "accepted": true
}
```

But the sdk requires a non-null snapshot:

```java
	private CreateSnapshotResponse(Builder builder) {

		this.accepted = builder.accepted;
		this.snapshot = ApiTypeHelper.requireNonNull(builder.snapshot, this, "snapshot");

	}
```

Am I missing something here?

**Comment by swallez** [comment]
The upstream API specification has been fixed in https://github.com/elastic/elasticsearch-specification/pull/1326

The next pass of code generation will fix the issue.
