### ISSUE TITLE
HitsMetadata deserialization error

### ISSUE THREAD

**Issue by anton-filatov** [elastic/elasticsearch-java#146]
When search request has a parameter track_total_hits = false
```
            SearchRequest searchRequest = new SearchRequest.Builder()
                    ...
                    .trackTotalHits(t -> t.enabled(false))
                    .build();
```

Then search response does not have a "hits.total" field and deserialization fails with
```
co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'HitsMetadata.total'

	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch.core.search.HitsMetadata.<init>(HitsMetadata.java:68)
	at co.elastic.clients.elasticsearch.core.search.HitsMetadata.<init>(HitsMetadata.java:53)
	at co.elastic.clients.elasticsearch.core.search.HitsMetadata$Builder.build(HitsMetadata.java:220)
	at co.elastic.clients.elasticsearch.core.search.HitsMetadata$Builder.build(HitsMetadata.java:139)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:56)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1487)
```

**Comment by sothawo** [comment]
duplicate of #56, this should be fixed now.

**Comment by anton-filatov** [comment]
My fault, didnt thought to look for closed issues. Thanks for reply!
