### ISSUE TITLE
getFieldMapping error when several fields

### ISSUE THREAD

**Issue by OlivierRo** [elastic/elasticsearch-java#166]
(ElasticSearch java client 7.17.0)
When asking for several fields mapping at once with new Java client API
`GetFieldMappingResponse response = client.indices().getFieldMapping(g -> g.index("dt_xdf_wet_tropo_pre").fields("id", "uri"));`
get following exception :
`co.elastic.clients.json.UnexpectedJsonEventException: Unexpected JSON event 'KEY_NAME' instead of 'END_OBJECT'

	at co.elastic.clients.json.JsonpUtils.expectEvent(JsonpUtils.java:57)
	at co.elastic.clients.json.JsonpUtils.expectNextEvent(JsonpUtils.java:51)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:197)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.endpoints.DictionaryResponse.lambda$setupDictionaryResponseDeserializer$0(DictionaryResponse.java:148)
	at co.elastic.clients.json.ObjectDeserializer.parseUnknownField(ObjectDeserializer.java:205)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:174)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getFieldMapping(ElasticsearchIndicesClient.java:1062)
`
With only one field, it is ok

**Comment by sbrunot** [comment]
I also reproduced this issue with the following code:

```
RestClient restClient = RestClient.builder(new HttpHost("localhost", 9200)).build();
ObjectMapper om = new ObjectMapper();
JsonpMapper mapper = new JacksonJsonpMapper(om);
ElasticsearchTransport transport = new RestClientTransport(restClient, mapper);
ElasticsearchClient client = new ElasticsearchClient(transport);
GetFieldMappingRequest gfmRequest =  new GetFieldMappingRequest.Builder()
		.index("*")
		.fields("*")
		.build();
GetFieldMappingResponse gfmResponse = client.indices().getFieldMapping(gfmRequest);
```

**Comment by allanpoola** [comment]
can you verify, that before mentioned error is really fixed?

**Comment by OlivierRo** [comment]
Ok, i can check it but what version should i use ? 7.15.5 ?

Le mer. 13 juil. 2022 à 12:56, Allan Poola ***@***.***> a
écrit :

**Comment by swallez** [comment]
This will be released in versions 8.4.0 and 7.17.6. In the meantime, it is already available in `7.17.6-SNAPSHOT` from the snapshot repository at https://snapshots.elastic.co/maven/

**Comment by OlivierRo** [comment]
Ok, great, i will check tomorrow or more reasonably friday and i will tell
you then

Le mer. 13 juil. 2022 à 17:49, Sylvain Wallez ***@***.***> a
écrit :

**Comment by OlivierRo** [comment]
It's ok for me, error is fixed 👍

Merci

**Comment by allanpoola** [comment]
how long it usually takes to get released package from Maven repository? Still waiting 7.17.6 to be released via mvn...
