### ISSUE TITLE
[es/snapshot.restore] Missing required property 'RestoreResponse.snapshot'

### ISSUE THREAD

**Issue by synox** [elastic/elasticsearch-java#201]
### Java API client version

7.16.2 and 7.17.1

### Java version

java 11.0.14 2022-01-18 LTS

### Elasticsearch Version

7.16.2

### Problem description

Running snapshot restore with wait_for_completion=false does not work with the Java client. 

Call:
```java
            client
                    .snapshot()
                    .restore(r -> r
                                    .repository(snapshotRepositoryName)
                                    .snapshot(snapshotName)
                                    .indices(globPatterns)
                                    .renamePattern(renamePattern.getSearchRegex())
                                    .renameReplacement(renamePattern.getReplacementRegex())
                                    .includeAliases(false)
                                    .waitForCompletion(false)
```

Results in URI:
```
/_snapshot/myRepoName/cloud-snapshot-2022.02.23-asdf/_restore?wait_for_completion=false
```

Error:
```java
co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'RestoreResponse.snapshot'

	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch.snapshot.RestoreResponse.<init>(RestoreResponse.java:57)
	at co.elastic.clients.elasticsearch.snapshot.RestoreResponse.<init>(RestoreResponse.java:50)
	at co.elastic.clients.elasticsearch.snapshot.RestoreResponse$Builder.build(RestoreResponse.java:121)
	at co.elastic.clients.elasticsearch.snapshot.RestoreResponse$Builder.build(RestoreResponse.java:94)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at co.elastic.clients.elasticsearch.snapshot.ElasticsearchSnapshotClient.restore(ElasticsearchSnapshotClient.java:361)
	at co.elastic.clients.elasticsearch.snapshot.ElasticsearchSnapshotClient.restore(ElasticsearchSnapshotClient.java:377)
```

From what I understand, the server responds with `{"acknowledged":true}` but in the spec the "snapshot" is mandatory. See similar PR: https://github.com/elastic/elasticsearch-specification/pull/1326/files

**Comment by synox** [comment]
cc: @fabriziofortino

**Comment by swallez** [comment]
The current definition of this type indeed doesn't take into account `wait_for_completion=false` and expects snapshot information to be present in the response body.

Rather than just making this property optional, we need do define a better solution to correctly handle all the API endpoints that accept a `wait_for_completion` parameter. I opened https://github.com/elastic/elasticsearch-specification/issues/1767 to address this at the API specification level, which will then be implemented in the Java API client.
