### ISSUE TITLE
UnexpectedJsonEventException when using a GetAliasRequest setup with the name of a non existant alias

### ISSUE THREAD

**Issue by sbrunot** [elastic/elasticsearch-java#255]
### Java API client version

7.16.3

### Java version

1.8.0_311

### Elasticsearch Version

7.17.3

### Problem description

When running the following code:

```
  RestClient restClient = RestClient.builder(new HttpHost("localhost", 9200)).build();
  ObjectMapper om = new ObjectMapper();
  JsonpMapper mapper = new JacksonJsonpMapper(om);
  ElasticsearchTransport transport = new RestClientTransport(restClient, mapper);
  ElasticsearchClient client = new ElasticsearchClient(transport);

  GetAliasRequest request = new GetAliasRequest.Builder()
            // "does-not-exist" does not match an existing alias
            .name("does-not-exist")
            .build();

  GetAliasResponse response = client.indices().getAlias(request);
```
the call to the `getAlias` method throws the following exception:

```
 co.elastic.clients.json.UnexpectedJsonEventException: Unexpected JSON event 'VALUE_STRING' instead of '[START_OBJECT, KEY_NAME]'
	at co.elastic.clients.json.JsonpUtils.ensureAccepts(JsonpUtils.java:68)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:74)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:276)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getAlias(ElasticsearchIndicesClient.java:967)
```

The expectation for this scenario is to get an ElasticsearchException that clearly signal that the alias does not exist.

**Comment by l-trotta** [comment]
Thanks for the report! This was fixed in version 7.17 of the java client.
