### ISSUE TITLE
IndexPrivilege cannot deserialize role when xpack security is enabled with "indices:admin/aliases" in privileges

### ISSUE THREAD

**Issue by mingchuno** [elastic/elasticsearch-java#317]
### Java API client version

v8/v7

### Java version

11

### Elasticsearch Version

v8/v7

### Problem description

Reproducer: https://github.com/mingchuno/elasticsearch-java-client-issue-reproducer

Steps to reproduce:
1. Start an Elasticsearch server with `xpack.security.enabled=true` and create a password. [example](https://github.com/mingchuno/elasticsearch-java-client-issue-reproducer/blob/ab9faf3d4a45666cf8a64029fb257d23eec48a79/docker-compose.yml)
2. Call Get Role API with java client. [example](https://github.com/mingchuno/elasticsearch-java-client-issue-reproducer/blob/ab9faf3d4a45666cf8a64029fb257d23eec48a79/app/src/main/kotlin/dev/mcor/elasticsearch/App.kt#L37)
3. Exception is thrown due to library cannot deserialize "indices:admin/aliases" into enum for [IndexPrivilege](https://github.com/elastic/elasticsearch-java/blob/1f60e2b4828a4dbe0965f7992fcad2b56626aafe/java-client/src/main/java/co/elastic/clients/elasticsearch/security/IndexPrivilege.java)

```
Exception in thread "main" co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.security.IndicesPrivileges: Invalid enum 'indices:admin/aliases' (JSON path: remote_monitoring_agent.indices[1].privileges[3]) (line no=1, column no=3260, offset=-1)
	at co.elastic.clients.json.JsonEnum$Deserializer.deserialize(JsonEnum.java:95)
	at co.elastic.clients.json.JsonEnum$Deserializer.deserialize(JsonEnum.java:81)
	at co.elastic.clients.json.JsonEnum$Deserializer.deserialize(JsonEnum.java:51)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:316)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:280)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85)
```

Fix:

* Change [IndicesPrivileges.privileges](https://github.com/elastic/elasticsearch-java/blob/77f89a07bdfd4c96ce448e22006dcc79a0d10861/java-client/src/main/java/co/elastic/clients/elasticsearch/security/IndicesPrivileges.java#L58) into `List<String>` just like [ApplicationPrivileges](https://github.com/elastic/elasticsearch-java/blob/77f89a07bdfd4c96ce448e22006dcc79a0d10861/java-client/src/main/java/co/elastic/clients/elasticsearch/security/ApplicationPrivileges.java#L54)

**Comment by l-trotta** [comment]
Hello, thank you for reporting this! While I'm pretty sure that this specific issue was solved in the more recent versions of the client, currently the deserialization of the response for the `role` API is failing for a different reason, which is the `transient_metadata` field not being optional. This is an [API specification definition](https://github.com/elastic/elasticsearch-specification) bug, which will be fixed soon, thus fixing the issue in the java client.
