### ISSUE TITLE
BulkRequest with scripted noop upsert UpdateOperation fails with "missing required property"

### ISSUE THREAD

**Issue by slovdahl** [elastic/elasticsearch-java#403]
### Java API client version

7.17.6

### Java version

1.8.0_345

### Elasticsearch Version

7.17.6

### Problem description

A bulk request with an update operation set to do scripted upsert where the script chooses to set `ctx.op = 'none'` currently fails with `co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'InlineGet.source'`. The same request works fine with the deprecated `RestHighLevelClient`.

```java
BulkResponse response = client.bulk(
        BulkRequest.of(bulkRequest -> bulkRequest
                .index("test-index")
                .operations(bulkOperation -> bulkOperation
                        .update(updateOperation -> updateOperation
                                .id(String.valueOf(1234))
                                .action(action -> action
                                        .scriptedUpsert(true)
                                        .upsert(ImmutableMap.of())
                                        .script(script -> script
                                                .inline(inlineScript -> inlineScript
                                                        .lang("painless")
                                                        .source("ctx.op = 'none';")
                                                )
                                        )
                                )
                        )
                )
        )
);
```

```
Error deserializing co.elastic.clients.elasticsearch.core.bulk.BulkResponseItem: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'InlineGet.source' (JSON path: items[0].get) (line no=1, column no=229, offset=-1)
co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.core.bulk.BulkResponseItem: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'InlineGet.source' (JSON path: items[0].get) (line no=1, column no=229, offset=-1)
	at co.elastic.clients.json.JsonpMappingException.from0(JsonpMappingException.java:134)
	at co.elastic.clients.json.JsonpMappingException.from(JsonpMappingException.java:121)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:206)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:316)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:280)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:328)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:294)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.bulk(ElasticsearchClient.java:310)
	at test.FailureTest.example(FailureTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        ...
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'InlineGet.source'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch._types.InlineGet.<init>(InlineGet.java:90)
	at co.elastic.clients.elasticsearch._types.InlineGet.<init>(InlineGet.java:58)
	at co.elastic.clients.elasticsearch._types.InlineGet$Builder.build(InlineGet.java:342)
	at co.elastic.clients.elasticsearch._types.InlineGet$Builder.build(InlineGet.java:214)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	... 75 more
```

**Comment by tuomoa** [comment]
Will this be fixed and is there workaround for this?

**Comment by l-trotta** [comment]
Hello and thank you for the report! This is an issue in the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code. Once the API specification is fixed, the Java client code will be updated to resolve this issue.

**Comment by technige** [comment]
@slovdahl Firstly, I'd like to apologise that you have had to wait so long for a reply. We have recently prioritised working through this backlog, so we should be able to keep on top of these issues much better going forward.

In terms of the details, you are absolutely right that this is a blocker to migration to the new client and ES8. That's not where we want to be. And I do recognise that your workarounds are temporary and non-optimal, but as @l-trotta mentions, we now have a fix for this particular issue in the pipeline.

I can't give you an exact date right now for when the fix will become available, but I can say that it should only be a matter of a few weeks before we get a patch release out. I hope this will help to unblock you.

Thanks again for your patience.

**Comment by l-trotta** [comment]
@slovdahl hey! The fix will be part of the next release 8.12.3, which should be out around the end of march :)

**Comment by slovdahl** [comment]
@l-trotta Awesome, thanks! Will it also be backported to the 7.17.x line?

**Comment by l-trotta** [comment]
yes!

**Comment by slovdahl** [comment]
Thanks, confirmed working with 7.17.19 :ok_hand: :bow:
