### ISSUE TITLE
Deseralizing index respose fails with "Missing required property 'ShardFailure.shard'" on index error

### ISSUE THREAD

**Issue by pvdlageweg** [elastic/elasticsearch-java#408]
### Java API client version

8.4.2

### Java version

17

### Elasticsearch Version

8.4.2

### Problem description

When doing an index request that fails because the high water mark is exceeded deserializing the response fails with the flowing stack trace:
`Exception in thread "main" co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch._types.ShardStatistics: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ShardFailure.shard' (JSON path: items[0]._shards.failures[0]) (line no=1, column no=538, offset=-1)
	at co.elastic.clients.json.JsonpMappingException.from0(JsonpMappingException.java:134)
	at co.elastic.clients.json.JsonpMappingException.from(JsonpMappingException.java:125)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:320)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:280)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:316)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:280)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:328)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:294)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.bulk(ElasticsearchClient.java:317)
	at com.mycompany.app.App.main(App.java:81)
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ShardFailure.shard'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch._types.ShardFailure.<init>(ShardFailure.java:72)
	at co.elastic.clients.elasticsearch._types.ShardFailure.<init>(ShardFailure.java:51)
	at co.elastic.clients.elasticsearch._types.ShardFailure$Builder.build(ShardFailure.java:240)
	at co.elastic.clients.elasticsearch._types.ShardFailure$Builder.build(ShardFailure.java:165)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:86)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48)
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:316)
	... 27 more
`

The JSON response is:

`{
  "took": 572,
  "errors": false,
  "items": [
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "reH2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99120,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "ruH2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99121,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "r-H2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99122,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "sOH2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99123,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "seH2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99124,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test1663930028722",
        "_id": "suH2aYMBzUrdPCfWN8pV",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 1,
          "failures": [
            {
              "_index": "test1663930028722",
              "_shard": 0,
              "_node": "6Xmgn4-9SD-B1s0ShGZnjw",
              "reason": {
                "type": "i_o_exception",
                "reason": "No space left on device",
                "suppressed": [
                  {
                    "type": "i_o_exception",
                    "reason": "No space left on device",
                    "suppressed": [
                      {
                        "type": "i_o_exception",
                        "reason": "No space left on device"
                      }
                    ]
                  }
                ]
              },
              "status": "INTERNAL_SERVER_ERROR",
              "primary": false
            }
          ]
        },
        "_seq_no": 99125,
        "_primary_term": 1,
        "status": 201
      }
    }
  ]
}`

**Comment by slovdahl** [comment]
I believe I got the same error with 7.17.6 and Java 8. I don't have the raw response unfortunately, it just saw the exception in CI logs:

```
co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch._types.ShardFailure: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ErrorCause.reason' (JSON path: _shards.failures[0].reason) (line no=1, column no=490, offset=-1)
        at co.elastic.clients.json.JsonpMappingException.from0(JsonpMappingException.java:134)
        at co.elastic.clients.json.JsonpMappingException.from(JsonpMappingException.java:121)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:206)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
        at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:85)
        at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48)
        at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:316)
        at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:280)
        at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
        at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
        at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
        at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
        at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
        at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
        at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:136)
        at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75)
        at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79)
        at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
        at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
        at co.elastic.clients.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:56)
        at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:328)
        at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:294)
        at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
        at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1458)
        at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1475)
        at app.App(App.java:876)
        Caused by:
        co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ErrorCause.reason'
            at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
            at co.elastic.clients.elasticsearch._types.ErrorCause.<init>(ErrorCause.java:82)
            at co.elastic.clients.elasticsearch._types.ErrorCause.<init>(ErrorCause.java:57)
            at co.elastic.clients.elasticsearch._types.ErrorCause$Builder.build(ErrorCause.java:381)
            at co.elastic.clients.elasticsearch._types.ErrorCause$Builder.build(ErrorCause.java:222)
            at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
            at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
            at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:71)
            at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:180)
            ... 34 more
```

**Comment by hdeweirdt** [comment]
+1, also encountered this today using ES version 8.13.4.

**Comment by cristinanegrean** [comment]
+1, also encountered this today, using ES version 8.17.4 with ES low level Java client version 8.15.5.

**Comment by cristinanegrean** [comment]
@Arnovandevelde we raised above with ELKaaS as well as a new support ticket.
