### ISSUE TITLE
The Watcher getWatch API does not return correctly a `compare` condition

### ISSUE THREAD

**Issue by bluttringer** [elastic/elasticsearch-java#422]
### Java API client version

8.4.3

### Java version

17.0.4-tem

### Elasticsearch Version

8.4.3

### Problem description

# Scenario

First create a watcher using REST API Put watcher :

```json
PUT _watcher/watch/my-watch
{
  "trigger": {
    "schedule": {
      "cron": "0 0/1 * * * ?"
    }
  },
  "input": {
    "search": {
      "request": {
        "indices": [
          "logstash*"
        ],
        "body": {
          "query": {
            "bool": {
              "must": {
                "match": {
                  "response": 404
                }
              },
              "filter": {
                "range": {
                  "@timestamp": {
                    "from": "{{ctx.trigger.scheduled_time}}||-5m",
                    "to": "{{ctx.trigger.triggered_time}}"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gt": 0
      }
    }
  },
  "actions": {
    "email_admin": {
      "email": {
        "to": "admin@domain.host.com",
        "subject": "404 recently encountered"
      }
    }
  }
}
```

This watcher is the one that is given as an example in the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/8.4/watcher-api-put-watch.html#watcher-api-put-watch-example)

Then, using the Java Client, try to get the watcher `my-watch`

```java
GetWatchResponse watch = client.watcher().getWatch(w ->
        w.id("my-watch"));
System.out.println("watcher = " + watch.watch());
```

The output is the following :

```
watcher = Watch: {"actions":{"email_admin":{"email":{"subject":"404 recently encountered","to":["admin@domain.host.com"]}}},"condition":{"compare":{}},"input":{"search":{"request":{"body":{"query":{"bool":{"filter":[{"range":{"@timestamp":{"from":"{{ctx.trigger.scheduled_time}}||-5m","to":"{{ctx.trigger.triggered_time}}"}}}],"must":[{"match":{"response":{"query":404}}}]}}},"indices":["logstash*"],"search_type":"query_then_fetch","rest_total_hits_as_int":true}}},"trigger":{"schedule":{"cron":"0 0/1 * * * ?"}}}
```
The `compare` condition is empty.
This is not a `toString()` problem, even debugging the code shows that the condition is empty.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/739167/195617032-deb6b4fc-3580-4d91-9647-4ee7ab7b5121.png">

As a consequence of (I suppose) the same kind of problem, trying to add the same watcher programmaticaly using the Java Client using this code :

```java
client.watcher().putWatch(p ->
           p.withJson(new StringReader(watcherDefinition)).id("my-watch"));
```

gives a JSON deserializing exception :

```
Exception in thread "main" co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/watcher.put_watch] failed: [parse_exception] could not parse [compare] condition for watch [my-watch]. expected an object for field [path] but found [VALUE_STRING] instead
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:281)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
	at co.elastic.clients.elasticsearch.watcher.ElasticsearchWatcherClient.putWatch(ElasticsearchWatcherClient.java:290)
	at co.elastic.clients.elasticsearch.watcher.ElasticsearchWatcherClient.putWatch(ElasticsearchWatcherClient.java:306)
	at com.edf.demo.runner.WatcherAPIClientRunner.run(WatcherAPIClientRunner.java:75)
	at com.edf.demo.App.main(App.java:54)
```

**Comment by bluttringer** [comment]
Made the test again using the 8.5.1 version of the client and everything is working as expected. Closing the issue.
