### ISSUE TITLE
IllegalArgumentException in toString()

### ISSUE THREAD

**Issue by fs-chris** [elastic/elasticsearch-java#424]
### Java API client version

8.4.3

### Java version

17

### Elasticsearch Version

8.4.3

### Problem description

Using the `toString()` method for requests containing `JsonData` leads to the below exception.
The shown exception happens on an `IndexSettings` object when logging it before sending.

```
 java.lang.IllegalArgumentException: Jackson's ObjectMapper can only be used with the JacksonJsonpProvider
 	at App.war//co.elastic.clients.json.jackson.JacksonJsonpMapper.serialize(JacksonJsonpMapper.java:87)
 	at App.war//co.elastic.clients.json.JsonDataImpl.serialize(JsonDataImpl.java:101)
 	at App.war//co.elastic.clients.elasticsearch.indices.IndexSettings.serializeInternal(IndexSettings.java:796)
 	at App.war//co.elastic.clients.elasticsearch.indices.IndexSettings.serialize(IndexSettings.java:788)
 	at App.war//co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:324)
 	at App.war//co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:261)
 	at App.war//co.elastic.clients.elasticsearch.indices.IndexSettings.toString(IndexSettings.java:1093)
```

**Comment by swallez** [comment]
Thanks for the report. This has been fixed in #440 and backported to the 8.5 and 7.17 branches.
