### ISSUE TITLE
Invalid enum values in DataStreamHealthStatus

### ISSUE THREAD

**Issue by Remcojansen88** [elastic/elasticsearch-java#43]
The enum in the DataStreamHealthStatus contains the wrong statuses, elastic return the status of the data stream in capitals. Currently the parsing of the object return a exception.

package co.elastic.clients.elasticsearch.indices.DataStreamHealthStatus

Green("green"),
Yellow("yellow"),
Red("red");

`
jakarta.json.stream.JsonParsingException: Invalid enum [GREEN]
	at co.elastic.clients.util.StringEnum$Deserializer.deserialize(StringEnum.java:75)
	at co.elastic.clients.util.StringEnum$Deserializer.deserialize(StringEnum.java:61)
	at co.elastic.clients.util.StringEnum$Deserializer.deserialize(StringEnum.java:45)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:102)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:68)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:122)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:95)
	at co.elastic.clients.json.BuildFunctionDeserializer.deserialize(BuildFunctionDeserializer.java:42)
	at co.elastic.clients.json.JsonpDeserializer$LazyDeserializer.deserialize(JsonpDeserializer.java:205)
	at co.elastic.clients.json.JsonpDeserializer$ArrayDeserializer.deserialize(JsonpDeserializer.java:430)
	at co.elastic.clients.json.JsonpDeserializer$ArrayDeserializer.deserialize(JsonpDeserializer.java:409)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:102)
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:68)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:122)
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:95)
	at co.elastic.clients.json.BuildFunctionDeserializer.deserialize(BuildFunctionDeserializer.java:42)
	at co.elastic.clients.json.JsonpDeserializer$LazyDeserializer.deserialize(JsonpDeserializer.java:205)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:102)
	at co.elastic.clients.base.RestClientTransport.getHighLevelResponse(RestClientTransport.java:231)
	at co.elastic.clients.base.RestClientTransport.performRequest(RestClientTransport.java:93)
	at co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient.getDataStream(ElasticsearchIndicesClient.java:838)`

**Comment by pullannagari** [comment]
@Remcojansen88 I am new to contributing to OS, can I pick this issue to fix?

**Comment by swallez** [comment]
Thanks for the report! This has been fixed in the upcoming 7.16, where various duplications of the health status enumeration have been unified as a common [`HealthStatus`](https://github.com/elastic/elasticsearch-java/blob/7.16/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/HealthStatus.java) type that accepts both upper-case and lower-case variants of the values.
