### ISSUE TITLE
TermvectorsResponse id is mandatory, even the id is optional on the request side. MissingPropertyException

### ISSUE THREAD

**Issue by dajogiXrm** [elastic/elasticsearch-java#451]
### Java API client version

8.5.1

### Java version

18

### Elasticsearch Version

8.5.0

### Problem description

TermvectorsResponse.id is mandatory even is optional on the request side. 

`co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'TermvectorsResponse.id'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch.core.TermvectorsResponse.<init>(TermvectorsResponse.java:72)
	at co.elastic.clients.elasticsearch.core.TermvectorsResponse.<init>(TermvectorsResponse.java:54)
	at co.elastic.clients.elasticsearch.core.TermvectorsResponse$Builder.build(TermvectorsResponse.java:275)
	at co.elastic.clients.elasticsearch.core.TermvectorsResponse$Builder.build(TermvectorsResponse.java:176)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:328)
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:294)
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.termvectors(ElasticsearchClient.java:1676)`

**Comment by stewseo** [comment]
Does sending the request with cURL or Postman return a value for the metadata field: _id? Posting the debug logs from org.elasticsearch.client.RestClient and the trace request string from org.elasticsearch.client.RequestLogger could help.

The documentation suggests disabling required properties checks if an incorrect MissingPropertiesException was thrown. 
- https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/missing-required-property.html

- https://github.com/elastic/elasticsearch-java/blob/8e4db1dea8897d3acfca72ab501be7c0bca91e5b/java-client/src/main/java/co/elastic/clients/elasticsearch/core/TermvectorsRequest.java#L187
- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html

**Comment by l-trotta** [comment]
Hello, thank you for the report! This seems correct to me, on the `TermvectorsRequest` side the `id` is optional, while on the `TermvectorsResponse` side it's mandatory as the server will always provide it. If this is still an issue, could you please send me an example of a call that fails with the reported error? I tried this out using the java client and couldn't reproduce it. Thanks :)
