### ISSUE TITLE
401 Unauthorized exception marked as JsonParsingException

### ISSUE THREAD

**Issue by Ayush1gupta** [elastic/elasticsearch-java#563]
### Java API client version

8.5.2

### Java version

11

### Elasticsearch Version

8.5.2

### Problem description

When indexing a document the api, 401 unauthorized exception is marked as **JsonParsingException** which hides the actual error.

**Error message**
`Caused by: jakarta.json.stream.JsonParsingException: Jackson exception: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

**Steps to reproduce.**
Setup a client with wrong password and index a document.

**Full stack trace**
`Caused by: jakarta.json.stream.JsonParsingException: Jackson exception: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 2]
	at co.elastic.clients.json.jackson.JacksonJsonpParser.convertException(JacksonJsonpParser.java:84) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.json.jackson.JacksonJsonpParser.fetchNextToken(JacksonJsonpParser.java:91) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.json.jackson.JacksonJsonpParser.next(JacksonJsonpParser.java:118) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:70) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:280) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148) ~[elasticsearch-java-8.5.2.jar:?]
	at co.elastic.clients.elasticsearch.ElasticsearchClient.index(ElasticsearchClient.java:962) ~[elasticsearch-java-8.5.2.jar:?]
`

**Comment by swallez** [comment]
The parsing error indicates that the response is most probably XML. Is it produced by an intermediate authenticating proxy?

#579 fixes exception parsing so that this situation will result in a `TransportException` that wraps a lower level `ResponseException` that contains the full http response.
