### ISSUE TITLE
Possible bug building SortOptions object from json

### ISSUE THREAD

**Issue by aianta** [elastic/elasticsearch-java#573]
### Java API client version

8.7.1

### Java version

19.0.1

### Elasticsearch Version

8.4.3

### Problem description

I'm trying to create a [SortOptions](https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/8.7.1/co/elastic/clients/elasticsearch/_types/SortOptions.html) object for an elastic search query using the [Create API objects from JSON data](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/loading-json.html#loading-json) method. But I keep getting the following exception:

```
class co.elastic.clients.json.JsonpDeserializer$3 cannot be cast to class co.elastic.clients.json.ObjectDeserializer (co.elastic.clients.json.JsonpDeserializer$3 and co.elastic.clients.json.ObjectDeserializer are in unnamed module of loader 'app')
java.lang.ClassCastException: class co.elastic.clients.json.JsonpDeserializer$3 cannot be cast to class co.elastic.clients.json.ObjectDeserializer (co.elastic.clients.json.JsonpDeserializer$3 and co.elastic.clients.json.ObjectDeserializer are in unnamed module of loader 'app')
    at co.elastic.clients.util.WithJsonObjectBuilderBase.withJson(WithJsonObjectBuilderBase.java:53)
    at co.elastic.clients.json.WithJson.withJson(WithJson.java:57)
    at ElasticsearchFromJsonTest.lambda$parseSortOptions$0(ElasticsearchFromJsonTest.java:27)
    at co.elastic.clients.elasticsearch._types.SortOptions.of(SortOptions.java:119)
    at ElasticsearchFromJsonTest.parseSortOptions(ElasticsearchFromJsonTest.java:27)
...
```

Code sample:

```java
import co.elastic.clients.elasticsearch._types.SortOptions;

import org.junit.jupiter.api.Test;
import java.io.StringReader;

public class ElasticsearchFromJsonTest {

    @Test
    void parseSortOptions(){

        String test = """
                {
                  "sort" : [
                    { "term" : "asc"}
                  ]
                }
                """;

        SortOptions so = SortOptions.of(b->b.withJson(new StringReader(test)));

    }

}
```
I've also tried setting test to:

```json
[{"term" : "asc"}]
```

And got the same results. I'll admit the 'bug' may just be in my simple minded interpretation of what subsection/format of json input is required to get this to work 😓, on the plus side that would be an easy fix.

**Comment by l-trotta** [comment]
Hello, thank you for the report! Definitely a bug, we'll investigate this.

**Comment by prchen** [comment]
For new guests to this issue, this comment may help you resolve this ancient issue temporarily 😂

I've figured out a possible solution by copying and override some source code:

1. Write a child class for `SortOptions.Builder`
2. Override `withJson` methods to make it works
3. Disable other builder methods to avoid state conflicts
4. Build `SortOptions` instance one-by-one for each item in the `sort` array

Code example:

```java
import co.elastic.clients.elasticsearch._types.*;
import co.elastic.clients.json.*;
import co.elastic.clients.util.ObjectBuilder;
import jakarta.json.stream.JsonParser;

import java.io.InputStream;
import java.io.Reader;
import java.io.StringReader;
import java.util.Objects;
import java.util.function.Function;

public class DummySortOptionBuilder extends SortOptions.Builder {
    private SortOptions build;

    @Override
    public ObjectBuilder<SortOptions> score(ScoreSort v) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> score(Function<ScoreSort.Builder, ObjectBuilder<ScoreSort>> fn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> doc(ScoreSort v) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> doc(Function<ScoreSort.Builder, ObjectBuilder<ScoreSort>> fn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> geoDistance(GeoDistanceSort v) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> geoDistance(Function<GeoDistanceSort.Builder, ObjectBuilder<GeoDistanceSort>> fn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> script(ScriptSort v) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> script(Function<ScriptSort.Builder, ObjectBuilder<ScriptSort>> fn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> field(FieldSort v) {
        throw new UnsupportedOperationException();
    }

    @Override
    public ObjectBuilder<SortOptions> field(Function<FieldSort.Builder, ObjectBuilder<FieldSort>> fn) {
        throw new UnsupportedOperationException();
    }

    @Override
    public SortOptions build() {
        return Objects.requireNonNull(build);
    }

    @Override
    public SortOptions.Builder withJson(InputStream input) {
        checkState();
        return super.withJson(input);
    }

    @Override
    public SortOptions.Builder withJson(Reader input) {
        checkState();
        return super.withJson(input);
    }

    @Override
    public SortOptions.Builder withJson(JsonParser parser, JsonpMapper mapper) {
        checkState();
        JsonpDeserializer<?> classDeser = JsonpMapperBase.findDeserializer(SortOptions.class);
        if (classDeser == null) {
            throw new IllegalArgumentException("Class " + this.getClass().getEnclosingClass() + " cannot be read from JSON");
        }

        // Generic parameters are always deserialized to JsonData unless the parent mapper can provide a deserializer
        mapper = new WithJsonMapper(mapper);

        @SuppressWarnings("unchecked")
        JsonpDeserializer<SortOptions> builderDeser =
                (JsonpDeserializer<SortOptions>) DelegatingDeserializer.unwrap(classDeser);
        this.build = builderDeser.deserialize(parser, mapper);
        return this;
    }

    private void checkState() {
        if (build != null) {
            throw new IllegalStateException();
        }
    }

    private static class WithJsonMapper extends DelegatingJsonpMapper {
        WithJsonMapper(JsonpMapper parent) {
            super(parent);
        }

        @Override
        public <T> T attribute(String name) {
            T attr = mapper.attribute(name);
            if (attr == null && name.startsWith("co.elastic.clients:Deserializer")) {
                @SuppressWarnings("unchecked")
                T result = (T) JsonData._DESERIALIZER;
                return result;
            } else {
                return attr;
            }
        }

        @Override
        public <T> JsonpMapper withAttribute(String name, T value) {
            return new WithJsonMapper(this.mapper.withAttribute(name, value));
        }
    }

    public static void main(String[] args) {
        SortOptions so = new DummySortOptionBuilder()
                .withJson(new StringReader("""
                        {"term" : "asc"}
                        """))
                .build();
        System.out.println(so);
    }
}

```

**Comment by li-a** [comment]
More directly, the workaround would be to avoid these two forms:

```
"sort" : [
    "_score"
]

"sort" : [
    { "myField": "asc" }
]
```

and instead, construct the JSON with the [most verbose form](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html):

```
"sort" : [
    { "_score": { "order": "desc" } }
]

"sort" : [
    { "myField": { "order": "asc" } }
]
```

**Comment by RyanHolstien** [comment]
Any movement on this? The issue is that this [_DESERIALIZER](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/SortOptions.java#L307) is set to the super type as compared to [Property](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/mapping/Property.java#L1825) for example.

This happens regardless of the form of the json string due to [this code](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/util/WithJsonObjectBuilderBase.java#L53)

The workaround posted by prchen above does work, but it would be nice to construct SortOptions from JSON without a hack from introspecting source code.

**Comment by l-trotta** [comment]
Hey everyone, thanks for your patience! The bug has been fixed and all future releases of the client will support the fix (from 8.17.x onward). The problem was that `SortOption` has a custom deserializer, since it allows various shortcut forms, and every class with a custom deserializer should implement the `withJson` method using that. `SortOptions` was missing the `withJson` implementation, thus using the generic deserializer, causing the failure. 

Just a clarification: the original example provided by @aianta is incorrect, since the "sort" json field is a level above the `SortOptions` object, and part of `SearchRequest`. So the correct forms for that test are either:

```java
@Test
void parseSortOptions(){

    String test = """
            {
                "term" : "asc"
            }
            """;
    SortOptions so = SortOptions.of(b->b.withJson(new StringReader(test)));

}
```
or 

```java

@Test
void parseSearchRequestWithSortOptions(){

   String test = """
            {
              "sort" : [
                { "term" : "asc"}
              ]
            }
            """;

   SearchRequest sr = SearchRequest.of(b->b.withJson(new StringReader(test)));

}
```
