### ISSUE TITLE
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ErrorResponse.status'

### ISSUE THREAD

**Issue by aditya2007** [elastic/elasticsearch-java#694]
### Java API client version

8.9.2 OR 8.10.4

### Java version

17

### Elasticsearch Version

8.9.2 (Elastic Cloud)

### Problem description

Getting below error while searching an index.
Caused by: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'ErrorResponse.status'

After adding below line 
        try (ApiTypeHelper.DisabledChecksHandle h =
                        ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true)) {...}
getting below error.

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "co.elastic.clients.util.ApiTypeHelper.requireNonNull(Object, Object, String)" is null
	at co.elastic.clients.elasticsearch._types.ErrorResponse.<init>(ErrorResponse.java:62)
	at co.elastic.clients.elasticsearch._types.ErrorResponse.<init>(ErrorResponse.java:52)
	at co.elastic.clients.elasticsearch._types.ErrorResponse$Builder.build(ErrorResponse.java:156)
	at co.elastic.clients.elasticsearch._types.ErrorResponse$Builder.build(ErrorResponse.java:114)
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:80)
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43)
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:336)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:140)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1897)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1914)
	at com.five9.ai.knowledge.service.ElasticConfig.main(ElasticConfig.java:68)

**Comment by aditya2007** [comment]
Issue Resolved with a clean build of my service
