### ISSUE TITLE
cannot create api key

### ISSUE THREAD

**Issue by uhdyi** [elastic/elasticsearch-java#711]
### Java API client version

8.11.1

### Java version

java zulu 17

### Elasticsearch Version

8.11.1

### Problem description

tried to create an api key but got error:
```
  public static String createApiKey() throws Exception {
    CreateApiKeyRequest request =
        new CreateApiKeyRequest.Builder().name("testcontainers-api-key").build();
    CreateApiKeyResponse createApiKeyResponse = client.security().createApiKey(request);
    System.setProperty("container.elasticsearch.apikey", createApiKeyResponse.apiKey());
    return createApiKeyResponse.apiKey();
  }

  private static ElasticsearchClient getElasticsearchClient() {
    RestClient restClient = getRestClient();
    final ObjectMapper mapper = new ObjectMapper();
    mapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    mapper.registerModule(new JavaTimeModule());

    ElasticsearchTransport transport =
        new RestClientTransport(restClient, new JacksonJsonpMapper(mapper));
    return new ElasticsearchClient(transport);
  }

  private static RestClient getRestClient() {
    final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
    credentialsProvider.setCredentials(
        AuthScope.ANY,
        new UsernamePasswordCredentials(
            System.getProperty("container.elasticsearch.username"),
            System.getProperty("container.elasticsearch.password")));

    return RestClient.builder(HttpHost.create(ELASTICSEARCH_CONTAINER.getHttpHostAddress()))
        .setHttpClientConfigCallback(
            httpClientBuilder -> {
              if (ELASTICSEARCH_CONTAINER.caCertAsBytes().isPresent()) {
                httpClientBuilder.setSSLContext(ELASTICSEARCH_CONTAINER.createSslContextFromCa());
              }
              return httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
            })
        .build();
  }
```

error:
```
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/security.create_api_key] failed: [http_status_405] Incorrect HTTP method for uri [/_security/api_key] and method [PUT], allowed: [POST]

	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
```

**Comment by swallez** [comment]
Thanks for the test code, but we could not reproduce the issue. The API key is created successfully.

We also tested two possible causes:
- the user not having api key creation privileges, but this returns `[security_exception] action [cluster:admin/xpack/security/api_key/create] is unauthorized...`
- [api keys being disabled](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#security-settings), but this returns `[feature_not_enabled_exception] api keys are not enabled`

The cause is certainly not related to the Java client but to your environment. Can you try the same request using `curl`, with the same login and password and see if it also fails:


```
ES_URL=...
ES_USER=...
ES_PASSWORD=...
curl -XPUT "http://$ES_URL/_security/api_key" -u $ES_USER:$ES_PASSWORD -H "Content-Type: application/json" -d'
{
  "name": "testcontainers-api-key"
}'
```

**Comment by l-trotta** [comment]
Hello, is this still an issue?
