### ISSUE TITLE
SortOptions not implement function deserialize(parser, mapper, event)

### ISSUE THREAD

**Issue by Dyqer** [elastic/elasticsearch-java#78]
When deserialize the json to SearchRequest

{
  "size": 9999,
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "modify_time": {
        "order": "desc"
      }
    }
  ],
  "track_total_hits": 2147483647
}
Array deserializer use function deserialize(parser, mapper, event) to deserialize each item in sort block, it will be failed because SortOptions not implement this function

**Comment by Dyqer** [comment]
@swallez Could you tell me where to get the code of specification to java generator ?

**Comment by jdrossl** [comment]
I found the same issue, here are some additional details

```bash
java.lang.UnsupportedOperationException: null
	at co.elastic.clients.json.JsonpDeserializer$2.deserialize(JsonpDeserializer.java:117) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:48) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:320) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:285) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:72) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:176) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:137) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:75) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:79) ~[elasticsearch-java-7.16.3.jar:?]
	at co.elastic.clients.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:43) ~[elasticsearch-java-7.16.3.jar:?]
```

This is the code I'm using:

```java
JsonParser parser = Json.createParser(inputStream);
JsonGenerator generator = mapper.jsonProvider().createGenerator(writer)) {
// Parse the request body in ES format
SearchRequest searchRequest = SearchRequest._DESERIALIZER.deserialize(parser, mapper);
```
