### ISSUE TITLE
co.elastic.clients.elasticsearch.ElasticsearchClient.delete responce nullpointerexception

### ISSUE THREAD

**Issue by miyaviYaKing** [elastic/elasticsearch-java#793]
### Java API client version

7.15.0

### Java version

21.0.3

### Elasticsearch Version

7.15.0

### Problem description

java.lang.NullPointerException: status
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at co.elastic.clients.base.ElasticsearchError.<init>(ElasticsearchError.java:44)
	at co.elastic.clients.base.ElasticsearchError$Builder.build(ElasticsearchError.java:120)
	at co.elastic.clients.json.BuildFunctionDeserializer.deserialize(BuildFunctionDeserializer.java:43)
	at co.elastic.clients.json.JsonpDeserializer$LazyDeserializer.deserialize(JsonpDeserializer.java:205)
	at co.elastic.clients.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:102)
	at co.elastic.clients.base.RestClientTransport.getHighLevelResponse(RestClientTransport.java:210)
	at co.elastic.clients.base.RestClientTransport.performRequest(RestClientTransport.java:93)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.delete(ElasticsearchClient.java:456)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.delete(ElasticsearchClient.java:473)

**Comment by miyaviYaKing** [comment]
I checked the kibana, found the "delete" can successfully delete the indexing, but also got this NPE

**Comment by miyaviYaKing** [comment]
ElasticsearchClient.delete can successfully remove the document, at the same time, throw the NPE

**Comment by l-trotta** [comment]
Hello! I tried reproducing this, but did not manage to trigger the exception. Could you send an example on how to reproduce this? Also version 7.15.0 is not supported anymore, you could try with the latest 7.X version, right now it's 7.17.21.
