### ISSUE TITLE
Elastic 8.15.3 and Rest High Level Client 7.17.24

### ISSUE THREAD

**Issue by igr** [elastic/elasticsearch-java#899]
### Java API client version

8.15.3

### Java version

21

### Elasticsearch Version

8

### Problem description

```
java.lang.NoSuchMethodError: 'org.elasticsearch.client.RequestOptions$Builder org.elasticsearch.client.RequestOptions$Builder.setHttpAsyncResponseConsumerFactory(org.elasticsearch.client.HttpAsyncResponseConsumerFactory)'
	at co.elastic.clients.transport.rest_client.SafeResponseConsumer.<clinit>(SafeResponseConsumer.java:52)
	at co.elastic.clients.transport.rest_client.RestClientOptions.initialOptions(RestClientOptions.java:191)
	at co.elastic.clients.transport.rest_client.RestClientOptions.of(RestClientOptions.java:52)
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.createOptions(RestClientHttpClient.java:84)
	at co.elastic.clients.transport.rest_client.RestClientHttpClient.createOptions(RestClientHttpClient.java:48)
	at co.elastic.clients.transport.ElasticsearchTransportBase.<init>(ElasticsearchTransportBase.java:109)
	at co.elastic.clients.transport.rest_client.RestClientTransport.<init>(RestClientTransport.java:36)
	at co.elastic.clients.transport.rest_client.RestClientTransport.<init>(RestClientTransport.java:32)
```

**Comment by l-trotta** [comment]
Hello, I don't really get what is the problem? If you want an example of how to use `setHttpAsyncResponseConsumerFactory` we have it in the [unit tests](https://github.com/elastic/elasticsearch-java/blob/d9cb8c51f1f4fb58806197b806078a1cd68f6774/java-client/src/test/java/co/elastic/clients/transport/rest_client/SafeResponseConsumerTest.java#L154) where we test the `SafeResponseConsumer`

**Comment by igr** [comment]
The issue is/was with different library versions when both old and new ES libraries are in use.

I fixed my issue with going back to one of the previous versions. I can't investigate more.

Closing this ticket as I cant provide a reproducible example
